"""
Alignment Mapping Agent.

Takes: Funder profile + Org knowledge
Produces: Strategic alignment brief

This is where the agent earns its keep.
The research agent gathers data.
THIS agent creates strategic intelligence.
"""

import os
from datetime import datetime
from tools.path import get_output_dir, get_safe_name


from tools.llm import call_llm
from tools.org_knowledge import get_full_context, search_org_knowledge, get_relevant_context, build_knowledge_base
from prompts.alignments import ALIGNMENT_SYSTEM_PROMPT, ALIGNMENT_PROMPT
    
from agents.reasercher import research_funder
from agents.connector import find_connection_paths

import config

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    console = Console()
except ImportError:
    class FallbackConsole:
        """Fallback when rich is not installed (e.g., Streamlit Cloud)"""
        def print(self, msg="", *args, **kwargs):
            import re as _re
            clean = _re.sub(r"\$$.*?\$$", "", str(msg))
            print(clean)
    class FallbackPanel:
        @staticmethod
        def fit(msg, **kwargs):
            return msg
    console = FallbackConsole()
    Panel = FallbackPanel
    Table = None



def create_alignment_brief(
    funder_name: str,
    funder_profile: str,
    org_context: str = None,
) -> dict:
        """
    Create a strategic alignment brief for a specific funder.    
    Args:
        funder_name: Name of the funder
        funder_profile: The profile generated by the research agent
                        (from Phase 1 — the .md file content)
        org_context:  org knowledge text. If not provided,
                     loads automatically from org_knowledge directory.
    
    Returns:
        Dict with alignment brief and metadata
    """
        console.print(Panel.fit(
            f"[bold blue]Alignment Mapping: {funder_name}[/bold blue]",
            border_style="blue"
            ))
            
        start_time = datetime.now()
        if org_context is None:
            console.print("[dim]Loading organization knowledge...[/dim]")
        
        # First, make sure ChromaDB is built
        from tools.org_knowledge import build_knowledge_base, get_relevant_context, get_full_context
        build_knowledge_base()
        
        console.print("[dim]Finding relevant org content for this funder...[/dim]")
        relevant_context = get_relevant_context(
            funder_priorities=funder_profile[:2000],  # Use start of profile as search
            n_results=10,  # top 10 most relevant chunks
        )
        
        full_context = get_full_context()
        
        org_context = (
            "=== MOST RELEVANT ORG CONTENT (semantic match) ===\n"
            f"{relevant_context}\n\n"
            "=== FULL ORGANIZATION OVERVIEW ===\n"
            f"{full_context}"
        )
    
        if "NO ORGANIZATION DOCUMENTS" in org_context:
            console.print("[red]Cannot create alignment — no org documents found![/red]")
            console.print("[yellow]Add documents to data/org_knowledge/ first.[/yellow]")
            return {"success": False, "error": "No org documents"}
    
        console.print(f"[dim]Org context: {len(org_context):,} chars[/dim]")
        console.print(f"[dim]Funder profile: {len(funder_profile):,} chars[/dim]")

        prompt = ALIGNMENT_PROMPT.format(
        funder_profile=funder_profile[:8000],
        org_knowledge=org_context[:12000],
    )

        console.print("[dim]Generating alignment analysis...[/dim]")
        console.print("[dim](This is the hard part — mapping two worldviews...)[/dim]")
        
        alignment_brief = call_llm(
            prompt=prompt,
            system_prompt=ALIGNMENT_SYSTEM_PROMPT,
            provider="gemini",
        )
        
        elapsed = (datetime.now() - start_time).total_seconds()
        
        result = {
            "success": True,
            "funder_name": funder_name,
            "alignment_brief": alignment_brief,
            "metadata": {
                "timestamp": datetime.now().isoformat(),
                "elapsed_seconds": round(elapsed, 1),
                "funder_profile_length": len(funder_profile),
                "org_context_length": len(org_context),
            },
        }
        
        # Save to file
        _save_alignment(funder_name, result)
        
        console.print(Panel.fit(
            f"[bold green]Alignment brief complete for {funder_name}[/bold green]\n"
            f"Time: {elapsed:.1f} seconds",
            border_style="green"
        ))
        
        return result


def _save_alignment(funder_name: str, result: dict):
        """Save alignment brief to file"""
        
        safe_name = funder_name.lower().replace(" ", "_")
        safe_name = "".join(c for c in safe_name if c.isalnum() or c == "_")
        
        output_dir = get_output_dir()
        os.makedirs(output_dir, exist_ok=True)
        
        filepath = os.path.join(output_dir, f"{safe_name}_alignment.md")
        
        with open(filepath, "w") as f:
            f.write(f"# Alignment Brief: {funder_name}\n")
            f.write(f"Generated: {result['metadata']['timestamp']}\n\n")
            f.write("---\n\n")
            f.write(result["alignment_brief"])
        
        console.print(f"  [dim]Saved: {filepath}[/dim]")


def full_pipeline(
    funder_name: str,
    website_url: str = None,
) -> dict:
    """
    COMPLETE pipeline: Research → Alignment → Connections
    
    This replaces full_research_and_alignment with the full chain.
    """
    
    console.print(Panel.fit(
        f"[bold blue]Full Pipeline: {funder_name}[/bold blue]\n"
        "Research → Alignment → Connection Paths",
        border_style="blue"
    ))
    
    # ---- Stage 1: Research ----
    console.print("\n[bold]═══ STAGE 1: FUNDER RESEARCH ═══[/bold]\n")
    research_result = research_funder(funder_name, website_url)
    
    # ---- Stage 2: Alignment ----
    console.print("\n[bold]═══ STAGE 2: ALIGNMENT MAPPING ═══[/bold]\n")
    alignment_result = create_alignment_brief(
        funder_name=funder_name,
        funder_profile=research_result["profile"],
    )
    
    # ---- Stage 3: Connections ----
    console.print("\n[bold]═══ STAGE 3: CONNECTION PATHS ═══[/bold]\n")
    connection_result = find_connection_paths(
        target_name=funder_name,
    )
    
    return {
        "funder_name": funder_name,
        "research": research_result,
        "alignment": alignment_result,
        "connections": connection_result,
    }
