"""Convert markdown reports to styled PDFs."""
import markdown
import pdfkit
from io import BytesIO
import datetime

PDF_CSS = """
<style>
    @page { size: A4; margin: 2cm; }
    body {
        font-family: -apple-system, 'Segoe UI', sans-serif;
        font-size: 11pt;
        line-height: 1.6;
        color: #2c3e50;
    }
    h1 { color: #1a365d; border-bottom: 3px solid #4FC3F7; padding-bottom: 8px; }
    h2 { color: #2c5282; margin-top: 24px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
    h3 { color: #2d3748; }
    code {
        background: #f7fafc;
        padding: 2px 6px;
        border-radius: 4px;
        font-family: 'Courier New', monospace;
        font-size: 10pt;
    }
    pre {
        background: #f7fafc;
        padding: 12px;
        border-radius: 6px;
        border-left: 4px solid #4FC3F7;
        overflow-x: auto;
    }
    blockquote {
        border-left: 4px solid #4FC3F7;
        padding-left: 16px;
        color: #4a5568;
        font-style: italic;
    }
    table {
        border-collapse: collapse;
        width: 100%;
        margin: 16px 0;
    }
    th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
    th { background: #edf2f7; font-weight: 600; }
    a { color: #2b6cb0; text-decoration: none; }
    .footer { color: #718096; font-size: 9pt; text-align: center; margin-top: 40px; }
</style>
"""


def markdown_to_pdf_bytes(md_content: str,funder_name:str, title: str = "Funder Intelligence Report") -> bytes:
    """
    Convert a markdown string into a styled PDF and return its bytes.
    
    Args:
        md_content: The markdown text
        title: Title used in the PDF metadata
    
    Returns:
        PDF file as bytes (ready for st.download_button)
    """
    # Convert markdown → HTML with extensions for tables, code blocks, etc.
    html_body = markdown.markdown(
        md_content,
        extensions=["extra", "tables", "fenced_code", "toc", "sane_lists"],
    )

    cover = f"""
    <div style="text-align:center; padding-top:30%; page-break-after:always;">
        <h1 style="font-size:32pt; color:#1a365d;">Funder Intelligence Report</h1>
        <h2 style="font-size:24pt; color:#2c5282; margin-top:20px;">{funder_name}</h2>
        <p style="margin-top:60px; color:#718096;">
            Generated {datetime.now().strftime('%B %d, %Y')}<br>
            Funder Intel Agent
        </p>
    </div>
    """
    # Wrap in full HTML document
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>{title}</title>
        {PDF_CSS}
    </head>
    <body>
        {html_body}
        <div class="footer">
            Generated by Funder Intel Agent · funder-intel-agent.streamlit.app
        </div>
    </body>
    </html>
    """

    # PDF options
    options = {
        "page-size": "A4",
        "margin-top": "20mm",
        "margin-right": "15mm",
        "margin-bottom": "20mm",
        "margin-left": "15mm",
        "encoding": "UTF-8",
        "no-outline": None,
        "footer-right": "Page [page] of [topage]",
        "footer-font-size": "8",
        "footer-spacing": "5",
        "enable-local-file-access": None,
    }

    pdf_bytes = pdfkit.from_string(full_html, False, options=options)
    return pdf_bytes